#!/usr/bin/env bash
# Derives the pinned build-input manifest from scripts/build-debug-apk.sh.
#
# The build script is the single source of truth for every pinned artifact.
# This script re-reads its configuration block and prints one row per input,
# so the manifest can be regenerated instead of maintained by hand:
#
#     .github/ci/generate-build-inputs.sh > .github/ci/build-inputs.tsv
#
# It only evaluates plain constant assignments from the configuration block.
# The three assignments that use command substitution are skipped: SCRIPT_DIR
# and PROJECT_ROOT are set here, and CODEX_ANDROID_ARCHIVE is resolved from
# the content-addressed cache layout instead of running the Codex helper.
#
# Columns: path (relative to the cache directory), sha256, origin, source url.
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd -P)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd -P)"
BUILD_SCRIPT="$PROJECT_ROOT/scripts/build-debug-apk.sh"

if [ ! -r "$BUILD_SCRIPT" ]; then
  echo "Cannot read the build script: $BUILD_SCRIPT" >&2
  exit 1
fi

# The configuration block ends where the first download_verified call begins.
config_end="$(grep -n '^download_verified "' "$BUILD_SCRIPT" | head -1 | cut -d: -f1)"
if [ -z "$config_end" ]; then
  echo "The build script no longer contains download_verified calls." >&2
  exit 1
fi

assignments="$(sed -n "1,${config_end}p" "$BUILD_SCRIPT" \
  | grep -E '^[A-Z_][A-Z0-9_]*=' \
  | grep -vE '^(SCRIPT_DIR|PROJECT_ROOT|CODEX_ANDROID_ARCHIVE)=')"
if printf '%s\n' "$assignments" | grep -qE '^[A-Z_][A-Z0-9_]*="?\$\('; then
  echo "Refusing to evaluate a configuration assignment that runs a command:" >&2
  printf '%s\n' "$assignments" | grep -E '^[A-Z_][A-Z0-9_]*="?\$\(' >&2
  exit 1
fi
eval "$assignments"

CACHE_DIR="${CACHE_DIR:-$PROJECT_ROOT/.cache/android}"

printf '# Pinned build inputs for scripts/build-debug-apk.sh\n'
printf '# Generated by .github/ci/generate-build-inputs.sh — do not edit by hand.\n'
printf '# Columns: path<TAB>sha256<TAB>origin<TAB>url ("-" when not downloadable).\n'
printf '# Paths are relative to the cache directory (AGENTCODI_CACHE_DIR,\n'
printf '# by default .cache/android).\n'

grep -E '^download_verified "' "$BUILD_SCRIPT" | while read -r _ url_ref sha_ref dest_ref; do
  url_name="$(printf '%s' "$url_ref" | tr -d '"$')"
  sha_name="$(printf '%s' "$sha_ref" | tr -d '"$')"
  dest_name="$(printf '%s' "$dest_ref" | tr -d '"$')"
  url="${!url_name-}"
  sha="${!sha_name-}"
  dest="${!dest_name-}"
  if [ -z "$url" ] || [ -z "$sha" ] || [ -z "$dest" ]; then
    echo "Unresolved download entry: $url_name $sha_name $dest_name" >&2
    exit 1
  fi
  printf '%s\t%s\tdownload\t%s\n' "${dest#"$CACHE_DIR"/}" "$sha" "$url"
done

# The Codex runtime is a locally built fork with no registry fallback. Its
# cache layout is content addressed: the directory name is the archive hash.
codex_dir="codex/$CODEX_ANDROID_SHA256"
printf '%s/package.tgz\t%s\tlocal\t-\n' "$codex_dir" "$CODEX_ANDROID_SHA256"
printf '%s/codex_app_server_protocol.schemas.json\t%s\tlocal\t-\n' \
  "$codex_dir" "$CODEX_SCHEMA_BUNDLE_SHA256"
printf '%s/codex_app_server_protocol.v2.schemas.json\t%s\tlocal\t-\n' \
  "$codex_dir" "$CODEX_V2_SCHEMA_BUNDLE_SHA256"
