package de.agentcodi.mcp;

public enum McpCatalogWarning {
    FEATURES_UNAVAILABLE,
    SKILLS_UNAVAILABLE,
    SKILL_LOAD_ERRORS,
    MCP_SERVERS_UNAVAILABLE,
    APPS_UNAVAILABLE,
    APP_DETAILS_INCOMPLETE,
    PLUGINS_UNAVAILABLE,
    MARKETPLACE_LOAD_ERRORS,
    CATALOG_TRUNCATED
}
